### ISSUE TITLE
Fulfil the open-source checklist

### ISSUE THREAD

**Issue by elbrujohalcon** [inaka/credo_server#28]
## General Items
- [x] It has a github repo
- [x] It has a proper Apache2 LICENSE file
- [ ] It's has a clear and useful README.md
- [ ] It's documented (with examples)
- [x] It's tested
- [x] It's hooked to the [open-source hipchat room](http://inaka.net/hipchat)
- [x] It has a link to the [open-source hipchat room](http://inaka.net/hipchat) in its README
- [x] It has a link to [inaka.github.io](http://inaka.github.io) in its README and/or landing page
## Exhibition
- [x] There is a blog post about it
- [ ] It's shared on social networks
- [ ] It's shared on reddit
- [ ] It's shared on hacker news with a title like Show HN: description
## For Elixir Projects
- [ ] It follows the rules for our [Project Setup](ELIXIR.md#project-setup)
  - [x] all default deps in hex.pm
  - [x] assigned to [HexFactor](https://beta.hexfaktor.org/)
  - [ ] proper data for hex.pm on mix.exs
  - [x] travis.yml up to date
## For Erlang/Elixir Projects
- [ ] It's shared on [Erlang Central](http://erlangcentral.org/add-news/)
